# This is a basic workflow to help you get started with Actions

name: Create PR main to develop

# Controls when the action will run. 
on:
  push:
    branches: [ main ]

jobs:
  create_pr:
    runs-on: ubuntu-latest
    
    env: 
     REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git

    steps:
    # checkout repository
    - name: checkout main branch
      uses: actions/checkout@v1
      with:
        ref: main
      
    # create PR
    - name: create PR
      run: |
        git config user.name sigarashi
        git config user.email 48591598+shigarashi1@users.noreply.github.com
        date > generated.txt
        git add .
        git commit -m "create: PR test"
        DATE=`date "+%Y%m%d_%H%M"`
        git checkout -b release/$DATE
        git push -u origin release/$DATE
