# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

# ワークフローの名前
name: Release GitHub Page

# 起動のタイミング
on:
  push:
    branches:
      - master

jobs:
  build:
    # 実行するインスタンス
    runs-on: ubuntu-latest

    # nodeのバージョン一覧
    strategy:
      matrix:
        node-version: ['12.18']

    # 各ステップの実行
    steps:
    
    # 環境変数設定
    - name: set env
      run: |
        DATE=`date "+%Y%m%d_%H%M"`
        TAG_NAME="release_$DATE"
        BRANCH_NAME="deployment/production"
        echo "DATE=$DATE, TAG_NAME=$TAG_NAME, BRANCH_NAME=$BRANCH_NAME"

    # チェックアウト
    - uses: actions/checkout@v1
    
    # ブランチ名変更
    - name: rename branch
      run: |
        git checkout -b $BRANCH_NAME

    # 使用するnodeのバージョンを指定
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    # build storybook
    - name: install npm package & build storybook
      run: |
        npm install
        npm run build-storybook
      env:
        CI: true
  
    # add git tag
    - name: add tag
      run: |
        git tag $TAG_NAME
        git push origin $TAG_NAME
    
    # force push
    - name: force push deployment/production
      run: |
        git add ./docs
        git commit -m 'release: $DATE'
        git push -f origin deployment/production
